### PR TITLE
Fix a bug where [FIRApp configure] is called multiple times.

### PR DESCRIPTION
**Pull request by noordawod**

### CODE REVIEW

**Comment by noordawod** [comment]
This fixes #41, and allows also the host app to configure FIR's default instance as it sees fit.

**Comment by taraspasichnyk** [comment]
When are you planning to merge this PR? @briemcnally @ladanazita @fathyb

**Comment by noordawod** [comment]
This project is dead, unfortunately.

**Comment by benevbright** [comment]
Nice. but I don't think this is a good solution, though.
Because it skips all the part of Segment-Firebase configure. 

I think we need an option to pass Segment-Firebase for not to call `[FIRApp configure];` here. 
And we do it ourselves as we want after this part.

**Comment by AdieOlami** [comment]
Was this fix used please?
I am having this issue and cannot figure it out

**Comment by briemcnally** [comment]
@AdieOlami this issue was fixed with our latest  release version 2.5.0:https://github.com/segment-integrations/analytics-ios-integration-firebase/blob/master/CHANGELOG.md#version-250-9th-september-2019. Please ensure you have the latest version installed. That being said, we went the approach outline in this PR: https://github.com/segment-integrations/analytics-ios-integration-firebase/pull/42 as to not skip the Segment-Firebase configuration.

**Pull request closed without merging**
