### PR TITLE
Chore: update firebase version to 9.3.0

### PR DESCRIPTION
**Pull request by mlazari**
Also update the example app's dependencies and add constraints to center the button on the screen (it was showing half outside the screen on iPhone 13 Pro Max simulator).

### CODE REVIEW

**Comment by saigkl** [comment]
When we can merge this to be merged?

**Comment by saigkl** [comment]
This is urgent and this is a pretty bug blocker for our app to take to prod.

**Review by knowledgebreak — APPROVED** [review]

**Comment by saigkl** [comment]
@knowledgebreak Any ETA on when this will be out?

**Comment by ariefwijaya** [comment]
@mlazari anw, now we need `9.5.0`

**Comment by julianfalcionelli** [comment]
I am also needing at least `9.4.0` ...

**Pull request closed without merging**
